# Generated by Django 6.0.2 on 2026-03-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('percentile', models.FloatField()),
                ('category', models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('NT', 'NT'), ('VJ', 'VJ')], max_length=20)),
                ('home_university', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.branch')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('NT', 'NT'), ('VJ', 'VJ')], max_length=20)),
                ('percentile', models.FloatField()),
                ('year', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.college')),
            ],
            options={
                'unique_together': {('college', 'branch', 'category', 'year')},
            },
        ),
    ]
