# Generated by Django 6.0.2 on 2026-03-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cet_percentile',
            new_name='percentile',
        ),
    ]
