# Generated by Django 6.0.2 on 2026-03-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('average_package', models.FloatField(blank=True, null=True)),
                ('highest_package', models.FloatField(blank=True, null=True)),
                ('hostel_available', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.college')),
            ],
        ),
    ]
