# Generated by Django 6.0.2 on 2026-02-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('percentile', models.FloatField()),
                ('year', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.college')),
            ],
            options={
                'unique_together': {('college', 'branch', 'category', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='Cuttoff',
        ),
    ]
