# Generated by Django 6.0.2 on 2026-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='home_university',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')]),
        ),
    ]
