# Generated by Django 6.0.2 on 2026-02-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0002_rename_branch_branch_name_alter_student_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoff',
            name='category',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('NT', 'NT'), ('VJ', 'VJ')], max_length=20),
        ),
    ]
