# Generated by Django 6.0.2 on 2026-03-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0002_collegedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedetail',
            name='cutoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predictorapp.cutoff'),
        ),
    ]
