# Generated by Django 6.0.2 on 2026-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0002_alter_student_home_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='home_university',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3),
        ),
    ]
