# Generated by Django 6.0.2 on 2026-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0003_alter_student_home_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('NT', 'NT'), ('VJ', 'VJ')], max_length=20),
        ),
    ]
