# Generated by Django 6.0.2 on 2026-03-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0003_collegedetail_cutoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegedetail',
            name='cutoff',
        ),
        migrations.AlterField(
            model_name='collegedetail',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.college'),
        ),
    ]
