# Generated by Django 6.0.2 on 2026-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0004_remove_collegedetail_cutoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentilePredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('percentile', models.FloatField()),
            ],
        ),
    ]
