# Generated by Django 6.0.2 on 2026-03-14 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0005_percentilepredictor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentcollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='predictorapp.userprofile')),
            ],
        ),
    ]
